### DISCUSSION TITLE
Build Squest image from docker compose

### DISCUSSION THREAD

**Discussion by pravyn** [HewlettPackard/squest#667] [General]
Hello,

First i want to say thank you for this amazing solution.

I' am trying to build image( squest ) from docker-compose file using the snippet below instead pulling from your quay repository. But i' am getting the below exception. Can you please help me on the best possible ways to work on your repo for local development.

****Code Snippiet**

 ```
 django: &django
    #image: ${SQUEST_IMAGE:-quay.io/hewlettpackardenterprise/squest}:${SQUEST_TAG:-latest}
    build:
      context: ./docker
      dockerfile: squest.Dockerfile
   
    env_file: docker/environment_variables/squest.env
    volumes:
      - django_static:/app/static
      - django_media:/app/media
      - backup:/app/backup
      - ./plugins/field_validators:/app/plugins/field_validators

```

**Below is the exception.**

```
squest-master-django-1         | [INFO  wait] --------------------------------------------------------
squest-master-django-1         | Applying database migration
squest-master-django-1         | python: can't open file '/app/manage.py': [Errno 2] No such file or directory
squest-master-django-1         | Collect static files
squest-master-django-1         | python: can't open file '/app/manage.py': [Errno 2] No such file or directory
squest-master-django-1         | Inserting default data
squest-master-django-1         | python: can't open file '/app/manage.py': [Errno 2] No such file or directory
squest-master-django-1         | Starting web server
squest-master-django-1         | [2023-09-15 09:13:23 +0000] [11] [INFO] Starting gunicorn 20.1.0
squest-master-django-1         | [2023-09-15 09:13:23 +0000] [11] [INFO] Listening at: http://0.0.0.0:8000 (11)
squest-master-django-1         | [2023-09-15 09:13:23 +0000] [11] [INFO] Using worker: sync
squest-master-django-1         | [2023-09-15 09:13:23 +0000] [12] [INFO] Booting worker with pid: 12
squest-master-django-1         | [2023-09-15 09:13:23 +0000] [12] [ERROR] Exception in worker process
squest-master-django-1         | Traceback (most recent call last):
```**
