### ISSUE TITLE
Add AWX docker image to the dev Docker compose

### ISSUE THREAD

**Issue by Sispheor** [HewlettPackard/squest#28]
So it can be used when dev and for integration test

- [ ] add AWX to compose 
- [ ] Add an Ansible playbook that print extra vars sent by squest and call the squest api to update the instance (URI module)
- [ ] Add Ansible playbook that configure AWX (create job template, create squest credential type, squest credential aka token, create Tower admin token)

**Comment by Sispheor** [comment]
Here is the generated docker compose file when using make file from AWX project
```yaml
version: '2.1'
services:
        # Primary AWX Development Container
  awx_1:
    user: "1000"
    image: "quay.io/awx/awx_devel:HEAD"
    container_name: tools_awx_1
    hostname: awx_1
    command: launch_awx.sh
    environment:
      OS: " Operating System: CentOS Linux 8"
      SDB_HOST: 0.0.0.0
      SDB_PORT: 7899
      AWX_GROUP_QUEUES: tower
      RECEPTORCTL_SOCKET: /var/run/receptor/receptor.sock
      RUN_MIGRATIONS: 1
    links:
      - postgres
      - redis_1
    working_dir: "/awx_devel"
    volumes:
      - "../../../:/awx_devel"
      - "../../docker-compose/supervisor.conf:/etc/supervisord.conf"
      - "../../docker-compose/_sources/database.py:/etc/tower/conf.d/database.py"
      - "../../docker-compose/_sources/websocket_secret.py:/etc/tower/conf.d/websocket_secret.py"
      - "../../docker-compose/_sources/local_settings.py:/etc/tower/conf.d/local_settings.py"
      - "../../docker-compose/_sources/SECRET_KEY:/etc/tower/SECRET_KEY"
      - "../../docker-compose/receptor.conf:/etc/receptor/receptor.conf"
      - "/sys/fs/cgroup:/sys/fs/cgroup"
      - "~/.kube/config:/var/lib/awx/.kube/config"
      - "redis_socket_1:/var/run/redis/:rw"
      - "receptor_1:/var/run/receptor/"
    privileged: true
    tty: true
    ports:
      - "7899-7999:7899-7999"  # sdb-listen
      - "6899:6899"
      - "8080:8080"  # unused but mapped for debugging
      - "8888:8888"  # jupyter notebook
      - "8013:8013"  # http
      - "8043:8043"  # https
  redis_1:
    image: redis:latest
    container_name: tools_redis_1
    volumes:
      - "../../redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "redis_socket_1:/var/run/redis/:rw"
    entrypoint: ["redis-server"]
    command: ["/usr/local/etc/redis/redis.conf"]
  # A useful container that simply passes through log messages to the console
  # helpful for testing awx/tower logging
  # logstash:
  #   build:
  #     context: ./docker-compose
  #     dockerfile: Dockerfile-logstash
  postgres:
    image: postgres:12
    container_name: tools_postgres_1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: awx
      POSTGRES_DB: awx
      POSTGRES_PASSWORD: xxxx
    volumes:
      - "awx_db:/var/lib/postgresql/data"
volumes:
  awx_db:
    name: tools_awx_db
  receptor_1:
    name: tools_receptor_1
  redis_socket_1:
    name: tools_redis_socket_1
```

The make script build the image locally but we could point to the [already built image from the quay.io ](https://quay.io/repository/ansible/awx)
