### ISSUE TITLE
Request does not changed from "PROCESSING" to "COMPLETE" (2025 edition)

### ISSUE THREAD

**Issue by kastl-ars** [HewlettPackard/squest#855]
Dear maintainers,

for some reason our Squest instance does no longer set the requests to `COMPLETE`, even if they were processed properly and finished in AWX. The requests stay in `PROCESSING`.

There is an old bug report from 2021: #126 

I already checked, both celery pods were running. Deleting them (which creates a new pod each) does not solve this issue.

There are no errors or suspicious log lines in the `squest` pod's logs.

This is happening for service requests created by "normal" users as well as for ones created by the `admin` user. 

Any ideas what could cause this?

Version v2.7.1 - 1c03fe

Kind Regards,
Johannes

**Comment by Sispheor** [comment]
The switch is done by Celery beat.

Seems to be related to K8S env. We need to dig.

**Comment by kastl-ars** [comment]
I had a look at both celery-worker and celery-beat logs. I also deleted both pods to have them re-created. This far no change, new and existing requests end up in `PROCESSING`.

Anything I should look out for in the logs?

**Comment by Sispheor** [comment]
On our side we had an issue with the vhost config. But we use our Ansible based deployment and not the community Helm chart.

Here is an example values for rabbitmq:
```yaml
           auth:
                password: rabbitmq
                username: rabbitmq
            extraConfiguration: |-
                load_definitions = /app/load_definition.json
            extraSecrets:
                load-definition:
                    load_definition.json: |-
                        {
                          "users": [
                            {
                              "name": "rabbitmq",
                              "password": "rabbitmq",
                              "tags": "administrator"
                            }
                          ],
                          "vhosts": [
                            {
                              "name": "/"
                            },
                            {
                              "name": "squest"
                            }
                          ],
                          "permissions":[
                            {
                                "user": "rabbitmq",
                                "vhost": "squest",
                                "configure": ".*",
                                "read": ".*",
                                "write": ".*"
                            }
                          ]
                        }
            loadDefinition:
                enabled: true
                existingSecret: load-definition
```
